### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by tom10271** [aletheia/iam-policy-generator#50]
```
{
    "name": "typescript-cli-starter",
    "private": true,
    "version": "1.0.0",
    "scripts": {
        "iam-policies": "ts-node src/aws-iam-generator/run.ts"
    },
    "dependencies": {
        "iam-policy-generator": "^2.0.4"
    },
    "devDependencies": {
        "@types/node": "^11.9.3",
        "ts-node": "^10.9.1",
        "typescript": "^4.9.5"
    }
}
```

src/aws-iam-generator/run.ts
```ts
import { Action } from 'iam-policy-generator';

console.log(Action);
```

```json
{
    "compilerOptions": {
        "target": "esnext",
        "module": "commonjs",
        "pretty": true,
        "sourceMap": true,
        "outDir": "dist",
        "importHelpers": true,
        "inlineSourceMap": true,
        "noImplicitAny": false,
        "strictNullChecks": false,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": false,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "strict": false,
        "preserveConstEnums": true,
        "noEmit": false,
        "moduleResolution": "node",
        "baseUrl": ".",
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "typeRoots": ["./types", "./node_modules/@types"]
    },
    "include": [
        "**/*.ts"
    ],
    "exclude": [
        "test/**",
        "**/*.test.ts"
    ]
}
```

---

Result
```
terraform-helper me$ npm run iam-policies 

> typescript-cli-starter@1.0.0 iam-policies
> ts-node src/aws-iam-generator/run.ts

/Project/DevOps/terraform-helper/node_modules/iam-policy-generator/dist/index.js:1
import * as Action from './generated/Actions';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .js] (/Project/DevOps/terraform-helper/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Project/DevOps/terraform-helper/src/aws-iam-generator/run.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

**Comment by tom10271** [comment]
I am not sure it is intended or not but I don't think anyone will use this library outside Node.js? Transpiling it into common.js would solve the problem.

Adding this into tsconfig.json then run `npm run compile`
`"module": "nodenext",`
